
services:
  app:
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    container_name: scriptorium_app
    volumes:
      - ./backend:/var/www
    working_dir: /var/www 
    ports:
      - "9501:9501"
    depends_on:
      - db
      - cache
    command: [ "php", "/var/www/bin/hyperf.php", "server:watch" ]
    networks:
    - scriptorium_network
  cache:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - scriptorium_network
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: scriptorium
      POSTGRES_USER: scripto
      POSTGRES_PASSWORD: scripto142536
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
    - scriptorium_network

  # frontend:
  #   build: ./frontend
  #   container_name: preact_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: ["npm", "run", "dev"]

networks:
  scriptorium_network:
