services:
  mongodb:
    image: mongo:5
    restart: on-failure
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - webapp-network
    mem_limit: 1g
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: on-failure
    hostname: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      # Unlimited amount of memory set for elasticsearch container
      memlock:
        soft: -1
        hard: -1
    # Resource limit for elasticsearch set to 1 gigabyte
    mem_limit: 1g
    ports:
      - 9200:9200
    networks:
      - webapp-network
  graylog:
    image: graylog/graylog:5.0.0
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_USERNAME=admin
      - GRAYLOG_PASSWORD_SECRET=142536142536142536
      - GRAYLOG_ROOT_PASSWORD_SHA2=023f5351b94db0bdcde8dd21da240ac75adc1fc82371c516543b25485cb900de
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongodb
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
    networks:
      - webapp-network
    mem_limit: 1g
volumes:
  mongo_data:
  es_data:
  graylog_data:
networks:
  webapp-network:
    driver: bridge
