services:
  backend:
    build:
      context: .
      dockerfile: ./backend/infra/php/Dockerfile
    container_name: scriptorium_backend_app
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    ports:
      - "9501:9501"
      - "9500:9500"
    depends_on:
      - db
      - cache
      - graylog
    command: >
      sh -c "
        composer install && 
        php /var/www/bin/hyperf.php migrate &&
        php /var/www/bin/hyperf.php start
      "
    networks:
      - scriptorium_network
    restart: unless-stopped

  frontend:
    container_name: scriptorium_frontend_app
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /frontend/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    networks:
      - scriptorium_network

  cache:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - scriptorium_network

  db:
    build:
      context: .
      dockerfile: ./backend/infra/postgres/Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: scriptorium
      POSTGRES_USER: scripto
      POSTGRES_PASSWORD: scripto142536
      LANG: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
      LC_CTYPE: pt_BR.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - scriptorium_network

  mongodb:
    image: mongo:5
    restart: on-failure
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - scriptorium_network
    mem_limit: 1g
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: on-failure
    hostname: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      # Unlimited amount of memory set for elasticsearch container
      memlock:
        soft: -1
        hard: -1
    # Resource limit for elasticsearch set to 1 gigabyte
    mem_limit: 1g
    ports:
      - 9200:9200
    networks:
      - scriptorium_network
  graylog:
    image: graylog/graylog:5.0.0
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
      - ./backend/infra/graylog/configure.sh:/usr/share/graylog/configure.sh
    environment:
      - GRAYLOG_USERNAME=admin
      - GRAYLOG_PASSWORD_SECRET=142536142536142536
      - GRAYLOG_ROOT_PASSWORD_SHA2=023f5351b94db0bdcde8dd21da240ac75adc1fc82371c516543b25485cb900de
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongodb
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201/tcp
      - 12201:12201/udp
    networks:
      - scriptorium_network
    mem_limit: 1g

networks:
  scriptorium_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  es_data:
  graylog_data:
