version: '3.8'

services:
  mongodb:
    image: mongo:5
    restart: on-failure
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    # command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    networks:
      - webapp-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: on-failure
    hostname: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      # Unlimited amount of memory set for elasticsearch container
      memlock:
        soft: -1
        hard: -1
    # Resource limit for elasticsearch set to 1 gigabyte
    mem_limit: 1g
    ports:
      - 9200:9200
    networks:
      - webapp-network
  graylog:
    image: graylog/graylog:5.0.0
    container_name: graylog
    volumes:
      - graylog_data:/usr/share/graylog/data # Persisted Graylog data
    environment:
      - GRAYLOG_PASSWORD_SECRET=142536142536142536
      - GRAYLOG_ROOT_PASSWORD_SHA2=ad0b4f988b42bf999fcc8ea6aee2ef75df8d11fee8b3625795313b97
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    # Command to run as soon as components are started
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    # Containers that Graylog depends on 
    links:
      - mongodb:mongodb
      - elasticsearch
    restart: always # Graylog container set to always restart when stopped
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - webapp-network
  # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
  es_data:
  graylog_data:
networks:
  webapp-network:
    driver: bridge
