name: CI - Scriptorium

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Environment PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: pcov, pdo_pgsql, redis, pdo, pdo_mysql, bcmath, swoole
          coverage: pcov

      - name: Install packages
        run: composer install --no-progress --prefer-dist
        working-directory: backend

      - name: Testing and coverage
        run: composer test && composer cover && cat coverage/junit.xml
        working-directory: backend

      - name: Static analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
